# Generated by Django 2.2.8 on 2020-01-17 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0002_profilefeeditem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilefeeditem',
            old_name='crated_on',
            new_name='created_on',
        ),
    ]
